# Generated by Django 3.2.15 on 2023-02-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_purchasedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
